name: _
publish_to: none
environment:
  sdk: '^3.9.2'
workspace:
  - commet
  - tiamat
  - widgets/matrix_widget_api
  - widgets/example_widget
  - widgets/calendar
dependencies:
  iso_duration: ^0.1.1
