name: commet
description: Find your space

publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.0.0
  google_fonts: ^4.0.3
  matrix: ^0.18.0
  flutter_olm: ^1.2.0
  flutter_openssl_crypto: ^0.1.0
  just_the_tooltip: ^0.0.12
  flutter_localizations:
    sdk: flutter
  intl: any
  intl_utils:
  desktop_drop: ^0.4.1
  test: ^1.22.0
  tiamat:
    path: ../tiamat/
  scaled_app: ^1.0.0
  crypto: ^3.0.2
  path: ^1.8.2
  path_provider: ^2.0.13
  widgetbook_annotation:
  flutter_markdown: ^0.6.9+1

  media_kit: ^0.0.8                              # Primary package.
  media_kit_video: ^0.0.10                       # For video rendering.
  media_kit_native_event_loop: ^1.0.4            # Support for higher number of concurrent instances & better performance.
  media_kit_libs_android_video: ^1.0.4           # Android package for video native libraries.
  media_kit_libs_ios_video: ^1.0.4               # iOS package for video native libraries.
  media_kit_libs_macos_video: ^1.0.5             # macOS package for video native libraries.
  media_kit_libs_windows_video: ^1.0.2           # Windows package for video native libraries.
  media_kit_libs_linux: ^1.0.2                   # GNU/Linux dependency package.
  hive: ^2.2.3
  hive_generator: ^1.1.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.0.18
  flutter_highlighter:
    git:
      url: https://github.com/commetchat/highlight.git
      path: ./flutter_highlighter
  file_picker: ^5.2.10
  html: ^0.15.2
  desktop_notifications: ^0.6.3
  url_launcher: ^6.1.11
  flutter_blurhash: ^0.7.0
  mime: ^1.0.4
  pasteboard: ^0.2.0
  flutter_local_notifications: ^14.1.0
  win_toast: ^0.3.0
  window_manager: ^0.3.4
  html_unescape: ^2.0.0
  build:
  scrollable_positioned_list: ^0.3.8
  flutter_staggered_grid_view: ^0.6.2
  http: ^0.13.6
  build_config: ^1.1.1

dev_dependencies:
  build_runner:
  widgetbook_generator:
  widgetbook:
  msix: ^3.7.0
  build:
  build_config:
  flutter_test:
    sdk: flutter

  integration_test:
    sdk: flutter

  flutter_launcher_icons:
  flutter_lints: ^2.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon/icon_square_512.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/app_icon/icon_circle_512.png"
  windows:
    generate: true
    image_path: "assets/images/app_icon/icon_circle_512.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/app_icon/icon_square_512.png"

flutter_intl:
  enabled: true # Required. Must be set to true to activate the plugin. Default: false
  class_name: T # Optional. Sets the name for the generated localization class. Default: S
  main_locale: en # Optional. Sets the main locale used for generating localization files. Provided value should consist of language code and optional script and country codes separated with underscore (e.g. 'en', 'en_GB', 'zh_Hans', 'zh_Hans_CN'). Default: en
  arb-dir: lib/l10n

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/placeholder/avatars/
    - assets/images/placeholder/generic/
    - assets/twemoji/assets/72x72/
    - assets/emoji_data/
    - assets/emoji_data/shortcodes/

  shaders:
    - assets/shader/texture_coordinate.frag

msix_config:
  display_name: Commet
  identity_name: chat.commet.app.windows-a33bc9ba
  toast_activator:
    clsid: "7685C041-9D17-4112-8FC4-386743A3D53E"
    arguments: "-ToastActivated"
    display_name: "Commet"
  msix_version: 1.0.4.0