name: commet
version: 0.0.1+1
publish_to: none
description: Your space to connect
environment: 
  sdk: '>=3.6.0 <4.0.0'
resolution: workspace

dependencies: 
  build: any
  build_config: ^1.1.1
  commet_calendar_widget:
    path: ../widgets/calendar
  matrix_widget_api:
    path: ../widgets/matrix_widget_api
  crypto: ^3.0.2
  desktop_drop: ^0.4.1
  desktop_notifications: ^0.6.3
  device_info_plus: ^11.3.0
  flutter_background_service: ^5.0.5
  flutter_blurhash: ^0.8.2
  flutter_markdown: ^0.6.9+1
  flutter_openssl_crypto: ^0.5.0
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.0.7
  html: ^0.15.2
  html_unescape: ^2.0.0
  http: ^1.1.0
  implicitly_animated_list: ^2.2.0
  intl: any
  intl_utils: any
  just_the_tooltip: ^0.0.12
  media_kit: ^1.2.0
  media_kit_libs_video: ^1.0.6
  media_kit_video: ^1.3.0
  mime: ^1.0.4
  pasteboard: ^0.2.0
  path: ^1.8.2
  path_provider: ^2.0.13
  permission_handler: ^11.0.1
  provider: ^6.0.0
  scrollable_positioned_list: ^0.3.8
  shared_preferences: ^2.5.2
  sqflite: ^2.3.0
  sqflite_common_ffi: ^2.3.0+4
  test: ^1.24.3
  unifiedpush: ^5.0.1
  universal_html: ^2.2.4
  url_launcher: ^6.1.11
  win_toast: ^0.4.0
  window_manager: ^0.5.1
  flutter: 
    sdk: flutter
  flutter_highlighter: 
    git: 
      url: https://github.com/commetchat/highlight.git
      path: ./flutter_highlighter
  flutter_html: 
    git: https://github.com/commetchat/flutter_html.git
  flutter_local_notifications: 
    git: 
      url: https://github.com/commetchat/flutter_local_notifications.git
      path: ./flutter_local_notifications
  flutter_localizations: 
    sdk: flutter

  tiamat: 
    path: ../tiamat/
  matrix:
    git: 
      url: https://github.com/commetchat/matrix-dart-sdk.git
      ref: upstream-v1.1.1
  matrix_dart_sdk_drift_db:
    git: 
      url: https://github.com/commetchat/matrix-dart-sdk-drift-db.git
      ref: upstream-v1.1.1+patch.2

  signal_sticker_api: 
    git: 
      url: https://github.com/commetchat/signal-sticker-api.git
      ref: f3295318c27d420f195e00164f104ead9aaa6209
  starfield: 
    git: https://github.com/lagmachine-com/starfield.git
  sqlite3_flutter_libs: ^0.5.23
  fuzzy: ^0.5.1
  drift: ^2.28.1
  archive: ^3.6.1
  exif: ^3.3.0
  image: ^4.2.0
  livekit_client: ^2.5.1
  flutter_webrtc: ^1.2.0
  file_picker: ^10.2.0
  flutter_web_auth_2: ^4.1.0
  receive_intent:
    git:
      url: https://github.com/daadu/receive_intent
      ref: master
  flutter_shortcuts_new: ^2.0.0
  flutter_vodozemac: ^0.2.2
  vodozemac: ^0.2.0
  intl_translation: ^0.20.1


  ## ---- Putting some extra lines in here to help git with the diff
  ## ---- Probably good to keep this stuff at the bottom of the list
  ## Begin Google Services Dependencies
  #firebase_core: ^2.30.0
  #firebase_messaging: ^14.7.10
  ## End Google Services Dependencies
  ## ----
  ## ----
  markdown: any
  collection: any
  webrtc_interface: any
  uuid: any
  flutter_background: ^1.3.0+1
  icalendar_parser: ^2.1.0
  image_picker: ^1.2.1
  timezone: ^0.10.1
  flutter_timezone: ^5.0.1
dependency_overrides:
  analyzer: ^7.3.0

  ## For inline-reply 
  flutter_local_notifications_linux: 
    git: 
      url: https://github.com/commetchat/flutter_local_notifications.git
      path: ./flutter_local_notifications_linux

  ## fixes: https://github.com/dart-lang/tools/issues/2169
  markdown:
    git:
      url: https://github.com/Airyzz/dart-lang-tools
      ref: main
      path: pkgs/markdown

dev_dependencies: 
  drift_dev: ^2.28.0
  build_runner: ^2.4.11
  flutter_launcher_icons: ^0.13.1
  msix: ^3.7.0
  pubspec_dependency_sorter: ^1.0.4
  flutter_test: 
    sdk: flutter
  integration_test: 
    sdk: flutter
  file: any
  
flutter_intl: 
  class_name: T
  main_locale: en
  arb_dir: assets/l10n

flutter_launcher_icons: 
  image_path: assets/images/app_icon/app_icon_filled.png
  adaptive_icon_background: '#534CDD'
  adaptive_icon_foreground: assets/images/app_icon/app_icon_transparent.png
  web: 
    image_path: assets/images/app_icon/app_icon_transparent_cropped.png
    generate: true
  windows: 
    image_path: assets/images/app_icon/app_icon_rounded.png
    generate: true
    icon_size: 48
  macos: 
    image_path: assets/images/app_icon/app_icon_rounded.png
    generate: true
  ios: null
  remove_alpha_ios: true
  android: true
  min_sdk_android: 16

flutter: 
  assets: 
    - assets/config/
    - assets/l10n/
    - assets/sound/
    - assets/images/app_icon/
    - assets/images/effects/particles/
    - assets/emoji_data/
    - assets/emoji_data/shortcodes/
    - assets/js/package/
    - assets/vodozemac/
  shaders: 
    - assets/shader/texture_coordinate.frag
    - assets/shader/star_trails.frag
  fonts: 
    - 
      family: Jellee
      fonts: 
        - 
          asset: assets/font/jellee/Jellee-Bold.ttf
    - 
      family: EmojiFont
      fonts: 
        - 
          asset: assets/font/emoji-font/TwemojiCOLR.otf
    - 
      family: RobotoCustom
      fonts: 
        - 
          asset: assets/font/roboto/Roboto-Regular.ttf
        - 
          asset: assets/font/roboto/Roboto-Bold.ttf
          weight: 700
    - 
      family: Code
      fonts: 
        - 
          asset: assets/font/code/JetBrainsMono-Regular.ttf
  uses-material-design: true
  generate: true

msix_config: 
  display_name: Commet
  identity_name: chat.commet.app.windows-a33bc9ba
  msix_version: 1.0.4.0
  toast_activator: 
    clsid: 7685C041-9D17-4112-8FC4-386743A3D53E
    arguments: -ToastActivated
    display_name: Commet
